### ISSUE TITLE
Add missing constraints to state circuit spec

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-specs#203]
- [x] CallContext
- [x] TxRefund
- [x] TxAccessListAccount
- [x] TxAccessListAccountStorage
- [ ] AccountDestructed

Circuit implementation related issue: https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/568

**Comment by ashWhiteHat** [comment]
# Todo
- [ ] create state circuit check list
- [ ] complete state circuit
- [ ] add prev value constraints

## Related Issues
- [Finish all target of read-write consistency check](https://github.com/privacy-scaling-explorations/zkevm-specs/issues/64)
- [Coherence between state/storage updates in state circuit - MPT circuit](https://github.com/privacy-scaling-explorations/zkevm-specs/issues/217)
- [Redundant constraints between circuits that share a table](https://github.com/privacy-scaling-explorations/zkevm-specs/issues/221)
- [check possible redundant constrain between copy circuit and state circuit](https://github.com/privacy-scaling-explorations/zkevm-specs/issues/232)

## Reference
- [ZKEVM - State Circuit - Design Rationale](https://hackmd.io/VCGteyZEQFKUjHA_A72f1Q#fn6)
- [state db in geth](https://github.com/ethereum/go-ethereum/blob/master/core/state/statedb.go#L65)
- [State Proof](https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/specs/state-proof.md)
- [State Circuit](https://github.com/privacy-scaling-explorations/zkevm-docs/blob/main/src/architecture/state-circuit.md)

## Completed Related Issue
- [fix state circuit order and packing issue](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/561)
- [Add missing constraints to state circuit](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/551)
- [implement tx log state circuit part](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/546)
- [Extend negative tests in the state circuit](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/534)
- [Update state circuit according to specs](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/356)
- [[state circuit] implement the new spec](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/350)
- [State Circuit Tracker](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/568)

**Comment by ashWhiteHat** [comment]
`AccountDestructed` is on hold because SELFDESTRUCT is on hold.
https://github.com/privacy-scaling-explorations/zkevm-specs/issues/259#issuecomment-1344003567

**Comment by ashWhiteHat** [comment]
close because of https://github.com/privacy-scaling-explorations/zkevm-specs/issues/203#issuecomment-1404806914
