### ISSUE TITLE
Synchronize State Circuit

### ISSUE THREAD

**Issue by ashWhiteHat** [privacy-scaling-explorations/zkevm-specs#364]
# Todo
- [x] out dated api modification https://github.com/privacy-scaling-explorations/zkevm-specs/issues/230
- [x] copy table sync https://github.com/privacy-scaling-explorations/zkevm-specs/issues/377
- [x] rw table sync https://github.com/privacy-scaling-explorations/zkevm-specs/issues/376
- [ ] synchronize prev column https://github.com/privacy-scaling-explorations/zkevm-specs/pull/415
- [ ] create error execution state synchronizing status
- [x] cover test https://github.com/privacy-scaling-explorations/zkevm-specs/pull/389#pullrequestreview-1387569997

## Contraints

|Resource|Constraints|Circuit|Spec|Synchronized|
|---|---|---|---|---|
|Start|1.0|🍗|🍗|✅|
||1.1|🍗|🍗|✅|
||1.2|🍗|🍗|✅|
||1.3|🍗|🍗|✅|
||1.4|🍗|🍗|✅|
||1.5|🍗|🐥|🚧|
|Memory|2.0|🍗|🍗|✅|
||2.1|🐔|🍗|🚧|
||2.2|🍗|🍗|✅|
||2.3|🍗|🍗|✅|
||2.4|🍗|🍗|✅|
||2.5|🍗|🍗|✅|
||2.6|🍗|🐥|🚧|
|Stack|3.0|🍗|🍗|✅|
||3.1|🍗|🍗|✅|
||3.2|🍗|🍗|✅|
||3.3|🍗|🍗|✅|
||3.4|🍗|🍗|✅|
||3.5|🍗|🍗|✅|
||3.6|🍗|🐥|🚧|
|Storage|4.0|🍗|🍗|✅|
||4.1|🍗|🍗|✅|
||4.2|🍗|🐥|✅|
|CallContext|5.0|🍗|🍗|✅|
||5.1|🍗|🍗|✅|
||5.2|🍗|🍗|✅||
||5.3|🍗|🍗|✅|
||5.4|🍗|🍗|✅|
||5.5|🍗|🐥|✅|
|Account Storage|6.0|🍗||✅|
||6.1|🍗|🐥|🚧|
||6.2|🍗|🐥|🚧|
|TxRefund|7.0|🍗|🍗|✅|
||7.1|🍗|🍗|✅|
||7.2|🍗|🍗|✅|
||7.3|🐥|🍗|✅|
||7.4|🍗|🐥|✅|
|TxAccessListAccount|8.0|🍗|🍗|✅|
||8.1|🍗|🍗|✅|
||8.2|🍗|🍗|✅||
||8.3|🍗|🍗|✅|
||8.4|🐥|🍗|✅|
||8.5|🍗|🐥|✅|
|TxAccessListAccountStorage|9.0|🍗|🍗|✅|
||9.1|🍗|🍗|✅|
||9.2|🍗|🍗|✅||
||9.3|🍗|🍗|✅|
||9.4|🐥|🍗|✅|
||9.5|🍗|🐥|✅|
|TxLog|10.0|🍗|🍗|✅|
||10.1|🍗|🍗|✅|
||10.2|🍗|🍗|✅||
||10.3|🍗|🐥|✅|
|TxReceipt|11.0|🐥|🍗|✅|
||11.1|🐥|🍗|✅|
||11.2|🐥|🍗|✅||
||11.3|🐥|🍗|✅|
||11.4|🍗|🍗|✅|
||11.5|🍗|🐥|✅|

Todo: 🥚
Checking:🐣
Implementing:🐥
Reviewing:🐔
Completed:🍗

## Related Issues
- [ ] [Finish all target of read-write consistency check](https://github.com/privacy-scaling-explorations/zkevm-specs/issues/64)
- [ ] [Coherence between state/storage updates in state circuit - MPT circuit](https://github.com/privacy-scaling-explorations/zkevm-specs/issues/217)
- [ ] [Redundant constraints between circuits that share a table](https://github.com/privacy-scaling-explorations/zkevm-specs/issues/221)
- [ ] [check possible redundant constrain between copy circuit and state circuit](https://github.com/privacy-scaling-explorations/zkevm-specs/issues/232)
- [x] [merge EVM circuit and state circuit](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/322)
- [ ] [Meta: CircuitInputBuilder progress status](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/222)

## Reference
- [ZKEVM - State Circuit - Design Rationale](https://hackmd.io/VCGteyZEQFKUjHA_A72f1Q#fn6)
- [state db in geth](https://github.com/ethereum/go-ethereum/blob/master/core/state/statedb.go#L65)
- [State Proof](https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/specs/state-proof.md)
- [State Circuit](https://github.com/privacy-scaling-explorations/zkevm-docs/blob/main/src/architecture/state-circuit.md)
- [State Circuit](https://hackmd.io/2j0HOVH8Qzi4peSZCs0d1g)

## Completed Related Issue
- [fix state circuit order and packing issue](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/561)
- [Add missing constraints to state circuit](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/551)
- [implement tx log state circuit part](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/546)
- [Extend negative tests in the state circuit](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/534)
- [Update state circuit according to specs](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/356)
- [[state circuit] implement the new spec](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/350)
- [State Circuit Tracker](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/568)

**Comment by aguzmant103** [comment]
Note: this could also be impacting the State Circuit 
https://github.com/privacy-scaling-explorations/zkevm-specs/issues/376
