### ISSUE TITLE
Towards Shanghai Upgrade

### ISSUE THREAD

**Issue by KimiWu123** [privacy-scaling-explorations/zkevm-specs#461]
Here's the list of EIPs in [Shanghai upgrade](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md):

- [ ] [EIP-3651: Warm COINBASE](https://eips.ethereum.org/EIPS/eip-3651) #457
- [ ] [EIP-3855: PUSH0 instruction](https://eips.ethereum.org/EIPS/eip-3855) #458
- [ ] [EIP-3860: Limit and meter initcode](https://eips.ethereum.org/EIPS/eip-3860) #459
- [ ] [EIP-4895: Beacon chain push withdrawals as operations](https://eips.ethereum.org/EIPS/eip-4895) #460
- [x] [EIP-6049: Deprecate SELFDESTRUCT](https://eips.ethereum.org/EIPS/eip-6049) This is noop, so no implementation is required.
